; This file was auto-generated by drush make
core = 7.x
api = 2

; set default dir
defaults[projects][subdir] = contrib

; Modules
projects[admin_menu][version] = "3.x-dev"

projects[addressfield][version] = "1.0-beta5"

projects[advanced_link][version] = "1.3"

projects[backup_migrate][version] = "2.8"

projects[better_formats][version] = "1.0-beta1"

projects[coder][version] = "2.2"

projects[ctools][version] = "1.4"

projects[captcha][version] = "1.1"

projects[ckeditor][version] = "1.15"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[email][version] = "1.3"

projects[emptyparagraphkiller][version] = "1.0-beta2"

projects[entity][version] = "1.5"

projects[entityconnect][version] = "1.0-rc1"

projects[entity_form][version] = "2.0-beta4"

projects[entity_view_mode][version] = "1.0-rc1"

projects[epsacrop][version] = "2.x-dev"
projects[epsacrop][patch][] = https://drupal.org/files/issues/epsacrop-requirements-block-installation-2237127-1.patch

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.2"

projects[field_collection][version] = "1.0-beta7"

projects[field_collection_fieldset][version] = "2.4"

projects[field_group][version] = "1.4"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "1.4"

projects[imageapi][version] = "1.x-dev"

projects[imce][version] = "1.9"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[logintoboggan][version] = "1.4"

projects[menu_admin_per_menu][version] = "1.0"

projects[module_filter][version] = "2.0-alpha2"

projects[menu_block][version] = "2.4"

projects[node_page_disable][version] = "1.0-rc2"

projects[password_policy][version] = "1.9"

projects[pathauto][version] = "1.2"

projects[pathauto_persist][version] = "1.3"

projects[prod_check][version] = "1.8"

projects[rabbit_hole][version] = "2.23"

projects[recaptcha][version] = "1.11"

projects[redirect][version] = "1.0-rc1"

projects[references][version] = "2.1"

projects[search404][version] = "1.3"

projects[search_krumo][version] = "1.5"

projects[securelogin][version] = "1.4"

projects[security_review][version] = "1.1"

projects[site_map][version] = "1.2"

projects[smart_trim][version] = "1.4"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[username_enumeration_prevention][version] = "1.0"

projects[uuid][version] = "1.0-alpha5"

projects[uuid_features][version] = "1.0-alpha4"

projects[views][version] = "3.8"

projects[vppr][version] = "1.0"

projects[xmlsitemap][version] = "2.0"

; Themes
projects[zen][version] = "5.4"
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[jquery.ui][download][type] = "file"
;libraries[jquery.ui][download][url] = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"
;libraries[jquery.ui][directory_name] = "jquery.ui/ui"
;libraries[jquery.ui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Jcrop][download][type] = "git"
libraries[Jcrop][download][url] = "https://github.com/tapmodo/Jcrop.git"
libraries[Jcrop][directory_name] = "Jcrop"
libraries[Jcrop][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery][download][type] = "file"
libraries[jquery][download][url] = "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
libraries[jquery][directory_name] = "jquery"
libraries[jquery][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = "git"
libraries[json2][download][url] = "https://github.com/douglascrockford/JSON-js.git"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

libraries[bootstrap][download][type] = "git"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap-sass.git"
libraries[bootstrap][download][tag] = "v3.1.1"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"